# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegitration2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_regitration2(self):
    # Test name: regitration2
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:5000/")
    # 2 | setWindowSize | 866x960 | 
    self.driver.set_window_size(866, 960)
    # 3 | click | linkText=sign up | 
    self.driver.find_element(By.LINK_TEXT, "sign up").click()
    # 4 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 5 | type | id=username | chiam
    self.driver.find_element(By.ID, "username").send_keys("chiam")
    # 6 | type | id=password | chiam@klij
    self.driver.find_element(By.ID, "password").send_keys("chiam@klij")
    # 7 | type | id=email | chiam@werdlr
    self.driver.find_element(By.ID, "email").send_keys("chiam@werdlr")
    # 8 | type | id=firstname | chiam
    self.driver.find_element(By.ID, "firstname").send_keys("chiam")
    # 9 | type | id=lastname | chiam
    self.driver.find_element(By.ID, "lastname").send_keys("chiam")
    # 10 | click | css=.box | 
    self.driver.find_element(By.CSS_SELECTOR, ".box").click()
    # 11 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 12 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
  
